name: Gh-Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'

      - name: Generate google-services.json
        run: |
          cat <<EOF > android/app/google-services.json
          {
            "project_info": {
              "project_number": "463169073060",
              "project_id": "vocabtranining",
              "storage_bucket": "vocabtranining.appspot.com"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:463169073060:android:eb8cf62cdcd0598f695b31",
                  "android_client_info": {
                    "package_name": "com.example.vocabulary_training"
                  }
                },
                "oauth_client": [],
                "api_key": [
                  {
                    "current_key": "${{ secrets.CURRENT_KEY }}"
                  }
                ],
                "services": {
                  "appinvite_service": {
                    "other_platform_oauth_client": []
                  }
                }
              }
            ],
            "configuration_version": "1"
          }
          EOF

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release

      - name: Extract Version Name and Code
        id: extract_version
        run: |
          versionName=$(grep '^version: ' pubspec.yaml | sed 's/version: //;s/+.*//')
          versionCode=$(grep '^version: ' pubspec.yaml | sed 's/.*+//')
          echo "VERSION_NAME=$versionName" >> $GITHUB_ENV
          echo "VERSION_CODE=$versionCode" >> $GITHUB_ENV

      - name: Rename Release APK
        run: |
          mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/app-release-${{ env.VERSION_NAME }}+${{ env.VERSION_CODE }}.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v1
        with:
          name: release-${{ env.VERSION_NAME }}+${{ env.VERSION_CODE }}-apk
          path: build/app/outputs/apk/release/app-release-${{ env.VERSION_NAME }}+${{ env.VERSION_CODE }}.apk

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Rename Debug APK
        run: |
          mv build/app/outputs/apk/debug/app-debug.apk build/app/outputs/apk/debug/app-debug-${{ env.VERSION_NAME }}+${{ env.VERSION_CODE }}.apk

      - name: Upload Debug APK
        uses: actions/upload-artifact@v1
        with:
          name: debug-${{ env.VERSION_NAME }}+${{ env.VERSION_CODE }}-apk
          path: build/app/outputs/apk/debug/app-debug-${{ env.VERSION_NAME }}+${{ env.VERSION_CODE }}.apk

  deploy-github-page:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: actions/setup-java@v2
        with:
            distribution: "zulu"
            java-version: "11"
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
      - name: Decode firebase_option
        env:
          firebase_options_dart: ${{secrets.FIREBASE_OPTION}}
        run : echo "$firebase_options_dart" > app/lib/firebase_options.dart
      - uses: subosito/flutter-action@v2
        with:
            channel: "stable"
      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{ secrets.APPID }}
            token: ${{ secrets.TOKEN }}
            groups: pre-tester
            file: build/app/outputs/apk/release/app-release.apk
            releaseNotes: "Release for ${{ github.ref }}\n\n${{ steps.get_tag_message.outputs.tag-message }}"
            releaseNotesFile: ''
            appRelease: ${{ steps.extract_version.outputs.version }}
      - name: Deploy to GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /vocabulary_training/
          webRenderer: canvaskit